name: Build and release WpfRenderer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore ./WpfRenderer/sanjigen.WpfRenderer.csproj

    - name: Publish
      run: dotnet publish ./WpfRenderer/sanjigen.WpfRenderer.csproj -c Release -o release --nologo -r win-x64 -p:PublishSingleFile=true --self-contained false
      
    - name: Zip up release folder
      run: |
        New-Item -ItemType Directory -Force publish
        Get-ChildItem .\release\ | Compress-Archive -DestinationPath "publish/dev-win-x64.zip"

    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          publish/*.zip